### ISSUE TITLE
Visitor Form: clicking close icon did not close the form; clicking Cancel button reset the form, but did not close the form.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#125]
Screenshot Example

![Visitor_Form_close_icon_Cancel_buttonjpg](https://user-images.githubusercontent.com/11938477/57550330-1471b280-7334-11e9-9921-1e228b71d9f5.jpg)

**Comment by bilel-kedidi** [comment]
can't simulate the error. can you please try to check web console and see if there is any errors?

**Comment by LAlexMHllc** [comment]
Clicked an entry where Visit Status=Should Update Return Visitor; Visitor Form displays with visitor info filled in; clicking close icon or Cancel button just cleared the form; should also close the form.
