### ISSUE TITLE
Visitor Transactions - View All screen: clicking a checkmark (or other icon) should display details about that particular visit.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#142]
Screenshot Example

![visitor_transactions_screen_view_all_icon_click_display_visit_details](https://user-images.githubusercontent.com/11938477/57879003-6cebf880-77e9-11e9-89be-3db98605f26d.jpg)

**Comment by bilel-kedidi** [comment]
i did show all info
