### ISSUE TITLE
Visitors Log - Can't edit visitor information

### ISSUE THREAD

**Issue by basitmohammad** [MicroHealthLLC/mVMS#171]
If you click "Create/Update Visitor Info" then there are no fields where I can update or change actual information.

![2019_05_23_13_14_39_mVMS](https://user-images.githubusercontent.com/26909671/58272715-18063000-7d5d-11e9-91ae-aba8861923df.jpg)

**Comment by bilel-kedidi** [comment]
this button is not used anymore on the next update.
the reason we have these buttons is to make filter on some criteria ( missed sign out/ saved sign out ...)

**Comment by basitmohammad** [comment]
So how will editing of visitor information be done now?
