### ISSUE TITLE
Can we fix this so it looks nicer, more arranged and NOT stretch the image on image capture?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mVMS#180]
![image](https://user-images.githubusercontent.com/3675043/58964609-34eb2c00-877d-11e9-9da7-80bc11549db4.png)

**Comment by bilel-kedidi** [comment]
@LAlexMHllc 
please send me screenshot

**Comment by LAlexMHllc** [comment]
Screenshot of stretched image after June 6 edit

![FrankT](https://user-images.githubusercontent.com/11938477/59278341-ce0fbc00-8c2f-11e9-88eb-8455e4281915.jpg)

**Comment by bilel-kedidi** [comment]
it's not stretched

**Comment by bluenevus** [comment]
Its stretched vertically on the ipads after you take a picture.  That picture preview is stretched vertically

 

 

--- vr, Frank

**Comment by bluenevus** [comment]
its on the sign out screen.

**Comment by bilel-kedidi** [comment]
thanks 
fixed
