### ISSUE TITLE
Visit Agreement Screen - put more space between Clear and Back button (same as the other buttons)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#195]

**Comment by bilel-kedidi** [comment]
![Screenshot from 2019-06-11 13-02-51](https://user-images.githubusercontent.com/5988861/59270390-42a32480-8c49-11e9-8ed0-028600f459df.png)
the buttons are fixed here.
i decreased the space for other buttons (from 40 px to 30px, for responsive issues)
