### ISSUE TITLE
Users - Basic Information: clicked Upload; selected image; image did not display

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#199]
Screenshot Example

![upload_image_not_complete](https://user-images.githubusercontent.com/11938477/59219685-0dd39680-8b91-11e9-9512-cb19169508f1.jpg)

**Comment by bilel-kedidi** [comment]
this should be a bug from server (check permission @bluenevus )

**Comment by bilel-kedidi** [comment]
@bluenevus  check if minimagick is installed
