### ISSUE TITLE
Visitors Log screen - missing Time Out when Visit Status=Must Record Sign Out*

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#201]
Time Out should have value of date/time when visitor completed Sign Out form.

Screenshot Example

![visitors_log_missing_time_out_when_must_record_sign_out](https://user-images.githubusercontent.com/11938477/59221064-68babd00-8b94-11e9-9d7a-b56ced1ba730.jpg)

**Comment by bilel-kedidi** [comment]
This icon means that the used did not signout . so you should not see a time out
