### ISSUE TITLE
Visitor Transactions screen - Visitor Created should have Recorded by Admin Name, not Visitor

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#203]
Screenshot Example

![visitor_created_by_admin_name_not_visitor](https://user-images.githubusercontent.com/11938477/59225718-7164c080-8b9f-11e9-8fad-adb24c838328.jpg)

**Comment by bilel-kedidi** [comment]
No, The visitor created is created by himself. admin cannot create a visitor

**Comment by LAlexMHllc** [comment]
A first time visitor fills in the Sign In form; the admin creates the visitor with the info the visitor provided.
