### ISSUE TITLE
Visitors Sign Form - Sign In: missing input for First Visit: radio input for Yes and No

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#207]
When input for email is not on app, then display First Visit radio buttons for Yes and No.

Screenshot Example

![visitor_signin_form_missing_first_visit_radios_yes_no](https://user-images.githubusercontent.com/11938477/59288638-3cf61080-8c42-11e9-85e1-f1a27d2e0930.jpg)

**Comment by bilel-kedidi** [comment]
@LAlexMHllc https://github.com/MicroHealthLLC/mVMS/issues/39
i think i found another bug related to this. all return visit is saved as a new return visit
now i do compare between info
if they are equivalent, i do not updte the info
