### ISSUE TITLE
Visitors Sign Form - Sign In: missing input for Update Info checkbox when First Visit=No

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#208]
Screenshot Example

![visitor_signin_form_missing_update_checkbox_when_first_visit_no](https://user-images.githubusercontent.com/11938477/59288823-a5dd8880-8c42-11e9-825b-20e15aa4b362.jpg)

**Comment by bilel-kedidi** [comment]
related: https://github.com/MicroHealthLLC/mVMS/issues/207
