### ISSUE TITLE
Visitors Log screen - visits more than one day ago where Time Out is blank have Visit Status=Should Update Visitor Info instead of Visit Status=Missed Sign Out...

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#223]

**Comment by bilel-kedidi** [comment]
Status Should Update Visitor Info  will display this formulat
![Screenshot from 2019-07-01 14-06-53](https://user-images.githubusercontent.com/5988861/60438870-93cf8400-9c09-11e9-953f-d33dbd20e78f.png)
So  the status "Missed Sign Out: Must Record Sign In/Out" is the right one
