### ISSUE TITLE
Admin user/password not working after last update

### ISSUE THREAD

**Issue by roncelis** [MicroHealthLLC/mVMS#227]
Hi,

After upgrading to the latest version, all admin accounts can't be used, it keeps returning that the passwords are invalid although they worked before the upgrade.

Without the admin account, we are unable to create new users and there is no way to change the admin password. 

Is there any way to update the admin password to a temp password so it can be changed?

Thanks

**Comment by bilel-kedidi** [comment]
added support for email in case password is forgotten
You have to go under config/email.yml and set your smtp credentials
