### ISSUE TITLE
Since visitor info will not be updated when avatar is blank, need to input "no image" icon so visitor info can be saved.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#236]
After clicking "Update" on Visitor Form, the message "Avatar can't be blank" displays; the visitor info can not be updated.

Screenshot Example

![avatar_can_not_be_blank_but_need_to_update_visitor_info](https://user-images.githubusercontent.com/11938477/60913167-d3731d00-a254-11e9-8f35-823a71c3ccd6.jpg)

**Comment by bilel-kedidi** [comment]
you can update visitor info without avatar now
