### ISSUE TITLE
When Return Visitor Signed In with prior visit without Sign Out, visitor was allowed to Sign In again. Should have been taken to complete Missed Sign Out. Note: Two Sign Ins were for same day and two were for an earlier dates.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#241]
Screenshot Example on Visitor Transactions screen

![signin_without_missed_signout_was_allowed](https://user-images.githubusercontent.com/11938477/60989337-b9e4da80-a313-11e9-9c1e-b649852da92c.jpg)

**Comment by bilel-kedidi** [comment]
this happen when we click twice to signin. fixed it
