### ISSUE TITLE
Visitors Log screen has Visitor Sign In Status="Return Visitor" with Visit Status="Missed Sign Out". Yet Visitor Transactions screen has 4 entries for this one visit, including Visit Sign In="First Time Visitor", all with same Date/Time. All missing Sign In Time and Missed Sign Out.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#266]
Screenshot Example

![Four_signin_for_one_trans_date_time_includes_first_and_returns](https://user-images.githubusercontent.com/11938477/63101533-39834c00-bf47-11e9-971a-ed5d265f6335.jpg)

**Comment by bilel-kedidi** [comment]
found the issue, it does happen whe we click multiple times to sign in button fixed it
