### ISSUE TITLE
".../visitor_log_all" screen - Filter for Visit Status = Missed Sign Out Completed should not include Visitor Missed Sign Out.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#310]
Screenshot Example

![visitor_log_all_filter_visitor_status_missed_sign_out_completed_do_not_include_missed_](https://user-images.githubusercontent.com/11938477/71674670-d3f2f900-2d49-11ea-9e3e-d0c62db914f7.jpg)

**Comment by bilel-kedidi** [comment]
this happen when sign out < sign in.
it's incoherent entry
