### ISSUE TITLE
Visitors Log screen: When missed sign out completed by visitor, that visit displays with filter for Visit Status = Visitor Signed Out instead of Visit Status = Missed Sign Out Completed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#318]
Screenshot Example

![visitors_log_visit_status_visitor_signed_out_includes_missed_sign_out_completed_by_visitor](https://user-images.githubusercontent.com/11938477/72908259-3f096d00-3d03-11ea-8895-420671ff0bb6.jpg)

**Comment by LAlexMHllc** [comment]
visitor_log and visitor_log_all

**Comment by bilel-kedidi** [comment]
this happen when signout < sign in
