### ISSUE TITLE
Include enumeration for Visit Reason on Setup Screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#32]

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/52418889-fdb18a80-2abc-11e9-979a-ec9ad5512e0c.png)

this way the user can just pick from a droplist vs type it in

**Comment by bluenevus** [comment]
we want to be able pick a drop down list on the visit reason so the user types less
