### ISSUE TITLE
unable to get into mvms setup, admin, people, companies screens

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mVMS#36]
![image](https://user-images.githubusercontent.com/3675043/47931751-24509b80-dea6-11e8-995e-34c9e4654702.png)

![image](https://user-images.githubusercontent.com/3675043/47931756-29ade600-dea6-11e8-8c43-6fd844e41a7a.png)

![image](https://user-images.githubusercontent.com/3675043/47931809-49450e80-dea6-11e8-9423-16dc675dcb30.png)

![image](https://user-images.githubusercontent.com/3675043/47931835-582bc100-dea6-11e8-9300-72303af9c549.png)

**Comment by bilel-kedidi** [comment]
@bluenevus : I need to get the log for this
