### ISSUE TITLE
Change logout icon to login icon on index (for admin) when not logged in

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#60]
Screenshot Example

![change_logout_icon_to_login_icon](https://user-images.githubusercontent.com/11938477/55164430-067c1f80-5142-11e9-885e-3c89f2df76e1.jpg)

**Comment by bluenevus** [comment]
Too complicated…lets just leave it be

 

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
Icon was changed to log-in

**Comment by bluenevus** [comment]
No lets just leave it be

 

Please close

 

--- vr, Frank
