### ISSUE TITLE
Input Log In button with function on Index screen (Welcome Visitors screen)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#8]
Example

![log_out_button_function](https://user-images.githubusercontent.com/11938477/41790340-433cb644-7620-11e8-9de4-08e74694102a.jpg)

**Comment by vasileiosmichalopoulos** [comment]
You can review the PR.

**Comment by bluenevus** [comment]
The url that button was supposed to go to is this  https://vms.microhealthllc.com/admin/  of course we don't want to hardcode https://vms.microhealthllc.com/ because others want to customize their own system but it should go to the /admin/ page after the base url the system is setup for
