### ISSUE TITLE
filtering updates

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mVMS#90]
filtering name doesn't work ie if I type first name or last name it wouldn't find it

We need to remove the default time in.  Its brutal to search when I want to see a name for all time then have to pick a date range.   There is no way to clear the date range...its always there.  Want to be able to search without a date range

there is no filter for visit reason
there is no search vor person visiting
there is no filter for us citizen
there is no filter for classified
there is no filter for the sign in status (text description)
there is no filter for visit status (text descriptions

can we move export csv to the upper right?

Can we move the search filters to be right above the  table grid?

Finally can have a sort feature for each of the headings?  by default it should sort on time in closest to farthest please

![image](https://user-images.githubusercontent.com/3675043/56681539-85a83900-6697-11e9-9953-51a0d6fb2c08.png)

**Comment by bilel-kedidi** [comment]
in progress:
What's done: 
- fixed name search 
there is no filter for visit reason
there is no search for person visiting
there is no filter for us citizen
there is no filter for classified
Can we move the search filters to be right above the table grid?
