### ISSUE TITLE
Remove "Back" link from New Person screen, since same function as "Cancel" button

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#92]

**Comment by bluenevus** [comment]
So there is a couple of pages.  So if you are on the 3rd page and want to go back, doesn’t it go back vs cancel?

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
Screenshot Example

![new_person_screen_remove_back_link](https://user-images.githubusercontent.com/11938477/57091417-22da2180-6cd7-11e9-8ea2-4c633df23675.jpg)
