### ISSUE TITLE
Reasons screen: change "New Reason" link to button and move position above page header (like People screen)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#93]

**Comment by bluenevus** [comment]
Need mockup please

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
Screenshot Example

![new_reason_link_to_button_change_position](https://user-images.githubusercontent.com/11938477/57091666-b1e73980-6cd7-11e9-9426-8c5cd237b624.jpg)
