### ISSUE TITLE
reasons/X screen: "Edit" and "Back" links should be buttons; position and style like people/X screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#94]

**Comment by bluenevus** [comment]
Need mockup please

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
Screenshot Example

![reason_show_screen_buttons_style_position](https://user-images.githubusercontent.com/11938477/57092026-7bf68500-6cd8-11e9-8141-5c0bc6186bd2.jpg)
