### ISSUE TITLE
Display Visitors Log Transactions table in descending Time In order so most recent date will be visible on first page

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mVMS#99]

**Comment by bilel-kedidi** [comment]
Could you send me a screenshot of the errors?

**Comment by LAlexMHllc** [comment]
Visitors Log is initially displayed in Time Out DESC instead of Time In DESC

![visitors_log_should_be_time_in_desc_NOT_time_out_desc](https://user-images.githubusercontent.com/11938477/58179652-a0f66c00-7c76-11e9-8792-517470770797.jpg)
